name: ai_based_smart_energy_meter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  audioplayers: ^6.1.0
  badges: ^3.1.2
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  fl_chart: ^0.70.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.3
  stacked: ^3.4.3
  stacked_firebase_auth: ^2.20.0
  stacked_services: ^1.1.0
  syncfusion_flutter_charts: ^27.2.5
  syncfusion_flutter_gauges: ^27.2.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/beep.mp3
    - assets/images/
    - assets/icons/
  fonts:
    - family: JimNightshade
      fonts:
        - asset: assets/fonts/Jim_Nightshade/JimNightshade-Regular.ttf


